name: Reuse other workflow

on: [workflow_dispatch]

env:
  PATH: "evanallen13/ActionFund-Test/.github/workflows/reusable.yml@main"

jobs:
  echo_path: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{env.PATH}}"
      
  # call-workflow:
  #   uses: ${{env.PATH}}
  #   with:
  #     who-to-greet: '@octocat'
    
  # use-output:
  #   runs-on: ubuntu-latest
  #   needs: [call-workflow]
  #   steps:
  #     - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
