name: Reuse other workflow

on: [workflow_dispatch]

jobs:
  setup: 
    runs-on: ubuntu-latest
    outputs:
      OWNER_NAME: ${{ steps.OWNER_NAME.outputs.OWNER_NAME }}
    steps:
      - id: OWNER_NAME
        run: echo "OWNER_NAME=${{github.repository_owner}}" >> "$GITHUB_OUTPUT"
        
  job2:
    runs-on: ubuntu-latest
    needs: setup
    steps:
        run: echo "${{needs.setup.outputs.OWNER_NAME}}"
      
  call-workflow:
    needs: setup
    uses: evanallen13/ActionFund-Test/.github/workflows/reusable.yml@main 
    with:
      who-to-greet: ${{github.repository_owner}}
    
  # use-output:
  #   runs-on: ubuntu-latest
  #   needs: [call-workflow]
  #   steps:
  #     - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
